sudo: required
services: docker
language: bash

jobs:
  include:
    - stage: test
      script:
        # build image
        - docker build -t martynas/kabrioletas-amd64 .

    - stage: deploy
      if: repo = 2m/kabrioletas-docker-amd64 AND tag =~ ^v
      script:
        # build image
        - docker build -t martynas/kabrioletas-amd64:${TRAVIS_TAG:1} .
        - docker tag martynas/kabrioletas-amd64:${TRAVIS_TAG:1} martynas/kabrioletas-amd64:latest

        - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        - docker push martynas/kabrioletas-amd64:${TRAVIS_TAG:1}
        - docker push martynas/kabrioletas-amd64

env:
  global:
    # travis encrypt DOCKER_USER=...
    - secure: "sGKm7e3IqKW5xmY/z2eFAl0ZLhBhEEXZYc7QwCe9ovnqfQauJIvwskvs2WKlqQoQS9xjhFPPE07XLIlWM7w4cjzPbE7wkYmjbFPeiwYkQXji2JdXD6XwYBFTOXyfq4Qr55Qq0TCIp7/cu2KVkOvyLOkZBwAjb494cpDPvjrYzbu2+iiyDMMoHAIAe4lF5Fe6RnOOEySTm1RDFx1UW1xcMowj4j+igfhfvfvIBA9EmEx6Y64rlluH/HVGevo65qnb1ht7BjLOvd93vgrHnxDA53+jYSK6Mj86RWbjz46lDE919s8eVFh2NTM95uw6Wl1y5aUlGWQUGb7k4UxKElNX/zdM0B0NgJioAo2GieFaVcfsuXmufyHH/4WgyjA6Osy4wi4uawg+XRWfnWcaB3TAbzr7I9WvCAg7WyCDYrHsYLafkwUMXbafRrC0x77Tc89kDhnk+O1+KomPKk/FctHtSGynR8HMVjzmaCJqNgGEHYZ0d0T7fkHtmcqKylsbvITkj1Xchbh1aOY/ey4tdY+xhdEK25oHRMv14tFNXkqS709BiaRGkxZnkplxqKGc4J8X6ikOG3AGuToNGTd0eWErTiuzPlK5U+lTvCctnuoSabIRmL+HE9sE2YNNKqjiGg3O/5mCPc9BiarQuadWpCVBO2Lxbenpg8Ral8BsjaBjdOs="
    # travis encrypt DOCKER_PASS=...
    - secure: "s7x0QKz7zppLS/MwoXhAus6suMa70dK4FC1aXqVApOyypaKGbYwIQxanJ5Mpu4AgVNgnqrEPyOk/CRonkbe0P1vFCeAx7WjtiiMYd2Lt0L5Y7tiN/UNkWUwmIibi9qFevpO0Y8mT7I0EdgvC1fjEw47ZVj3bLuj8TwrkgmhDTs/f/lYX5zEjVrV2obqQ9QZkvKp6uJB4U8FKSIrwCn8R7pl8JlT/VVlx4RDeZ6GcBo9vbVa34FzUroocF+1HHmTo9iIdRFJAjtbC+fK2/iXXS5cNQyYX6HpkubR4T8wtoIomPq8lGz0dZMeaudZCswW6BzreaoztNEjgJrBNi7u5yv2kLwTpnRlbK57zCE49c+B9Wco3g/T6FtqKtBnAE3MDVMjHTQkSBLfqhgOifcQampluxzaUv3EN7n1nGohQkekrDzjQ+arQ6GG6PopqsSO0fR69gg0Jpv7VX/hwvuOLpAMPKti9bOZzSU8l95bwaHCP2HRewGVzQvm7UtqGDnG7UF/jOAIFLW6xQKU65fel8zAnJFhSRoh7UzwbRQ4Hzo0SsD8d3f9dF62ovuyayGJP+eihvyciAIZKC3sdPUtQ/Fpov8seLoLWnTAs1dIqWR8g0xhGp5FyWsuaonW0HWb/062k7ReOdaLV4877j8zDYHKViXg/2HNAsNCMLCVZpXM="
